language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip3 install codecov
  - pip3 install pipenv
  - pipenv install
# command to run tests
script: python -m unittest tests/test_suite.py

after_success:
  - codecov